import { ASSETS } from "@/config";

const tickets = [
  {
    ticketType: "Standard Tickets",
    ticketPrice: "0.00",
    ticketLeft: "0",
  },
  {
    ticketType: "Executive Tickets",
    ticketPrice: "0.00",
    ticketLeft: "0",
  },
  {
    ticketType: "VIP Tickets",
    ticketPrice: "49,900.00",
    ticketLeft: "139",
  },
];

const users = [
  {
    _id: 1,
    first_name: "Kristine",
    last_name: "Pelman",
    email: "kpelman0@soup.io",
    gender: "female",
    verified: true,
    created_at: "3/12/2023",
    og: "userAction",
  },
  {
    _id: 2,
    first_name: "Elisha",
    last_name: "McQuillin",
    email: "emcquillin1@reverbnation.com",
    gender: "male",
    verified: false,
    created_at: "14/4/2024",
    og: "userAction",
  },
  {
    _id: 3,
    first_name: "Merissa",
    last_name: "Cockrem",
    email: "mcockrem2@washingtonpost.com",
    gender: "female",
    verified: false,
    created_at: "11/4/2024",
    og: "userAction",
  },
  {
    _id: 4,
    first_name: "Sharona",
    last_name: "Winfred",
    email: "swinfred3@skyrock.com",
    gender: "female",
    verified: false,
    created_at: "12/1/2024",
    og: "userAction",
  },
  {
    _id: 5,
    first_name: "Guendolen",
    last_name: "Daid",
    email: "gdaid4@baidu.com",
    gender: "female",
    verified: false,
    created_at: "24/4/2024",
    og: "userAction",
  },
  {
    _id: 6,
    first_name: "Philis",
    last_name: "Shone",
    email: "pshone5@mac.com",
    gender: "female",
    verified: true,
    created_at: "6/9/2023",
    og: "userAction",
  },
  {
    _id: 7,
    first_name: "Zebulen",
    last_name: "Stegel",
    email: "zstegel6@liveinternet.ru",
    gender: "male",
    verified: true,
    created_at: "27/4/2024",
    og: "userAction",
  },
  {
    _id: 8,
    first_name: "Russell",
    last_name: "Dondon",
    email: "rdondon7@webnode.com",
    gender: "male",
    verified: true,
    created_at: "22/12/2023",
    og: "userAction",
  },
  {
    _id: 9,
    first_name: "Gareth",
    last_name: "O'Tuohy",
    email: "gotuohy8@geocities.com",
    gender: "Genderqueer",
    verified: true,
    created_at: "18/10/2023",
    og: "userAction",
  },
  {
    _id: 10,
    first_name: "Joyann",
    last_name: "Koppe",
    email: "jkoppe9@nasa.gov",
    gender: "Genderfluid",
    verified: false,
    created_at: "19/8/2024",
    og: "userAction",
  },
  {
    _id: 11,
    first_name: "Arielle",
    last_name: "Odegaard",
    email: "aodegaarda@theguardian.com",
    gender: "female",
    verified: true,
    created_at: "13/2/2024",
    og: "userAction",
  },
  {
    _id: 12,
    first_name: "Ellen",
    last_name: "Lillo",
    email: "elillob@ovh.net",
    gender: "female",
    verified: false,
    created_at: "8/5/2024",
    og: "userAction",
  },
  {
    _id: 13,
    first_name: "Gerick",
    last_name: "Martinho",
    email: "gmartinhoc@guardian.co.uk",
    gender: "male",
    verified: true,
    created_at: "22/7/2024",
    og: "userAction",
  },
  {
    _id: 14,
    first_name: "Cletus",
    last_name: "Charville",
    email: "ccharvilled@apache.org",
    gender: "male",
    verified: true,
    created_at: "30/7/2024",
    og: "userAction",
  },
  {
    _id: 15,
    first_name: "Currie",
    last_name: "Stoppe",
    email: "cstoppee@scientificamerican.com",
    gender: "male",
    verified: false,
    created_at: "4/11/2023",
    og: "userAction",
  },
  {
    _id: 16,
    first_name: "Cammi",
    last_name: "Chittie",
    email: "cchittief@state.tx.us",
    gender: "female",
    verified: true,
    created_at: "26/5/2024",
    og: "userAction",
  },
  {
    _id: 17,
    first_name: "Jacquette",
    last_name: "Duell",
    email: "jduellg@booking.com",
    gender: "female",
    verified: false,
    created_at: "6/2/2024",
    og: "userAction",
  },
  {
    _id: 18,
    first_name: "Latrina",
    last_name: "Arkill",
    email: "larkillh@networkadvertising.org",
    gender: "female",
    verified: false,
    created_at: "14/8/2024",
    og: "userAction",
  },
  {
    _id: 19,
    first_name: "Luella",
    last_name: "Manuely",
    email: "lmanuelyi@ibm.com",
    gender: "female",
    verified: true,
    created_at: "29/8/2024",
    og: "userAction",
  },
  {
    _id: 20,
    first_name: "Elena",
    last_name: "Sagar",
    email: "esagarj@ow.ly",
    gender: "female",
    verified: true,
    created_at: "27/6/2024",
    og: "userAction",
  },
  {
    _id: 21,
    first_name: "Lorrin",
    last_name: "Summerley",
    email: "lsummerleyk@seesaa.net",
    gender: "female",
    verified: false,
    created_at: "18/9/2023",
    og: "userAction",
  },
  {
    _id: 22,
    first_name: "Ellis",
    last_name: "Wiggall",
    email: "ewiggalll@sciencedirect.com",
    gender: "male",
    verified: true,
    created_at: "25/4/2024",
    og: "userAction",
  },
  {
    _id: 23,
    first_name: "Bertrand",
    last_name: "Cohan",
    email: "bcohanm@gmpg.org",
    gender: "male",
    verified: true,
    created_at: "10/3/2024",
    og: "userAction",
  },
  {
    _id: 24,
    first_name: "Marwin",
    last_name: "Cuffin",
    email: "mcuffinn@163.com",
    gender: "male",
    verified: true,
    created_at: "29/7/2024",
    og: "userAction",
  },
  {
    _id: 25,
    first_name: "August",
    last_name: "Wartnaby",
    email: "awartnabyo@sphinn.com",
    gender: "male",
    verified: false,
    created_at: "28/5/2024",
    og: "userAction",
  },
  {
    _id: 26,
    first_name: "Derril",
    last_name: "Danelut",
    email: "ddanelutp@thetimes.co.uk",
    gender: "male",
    verified: true,
    created_at: "13/3/2024",
    og: "userAction",
  },
  {
    _id: 27,
    first_name: "Briant",
    last_name: "MacBey",
    email: "bmacbeyq@cnbc.com",
    gender: "male",
    verified: false,
    created_at: "21/3/2024",
    og: "userAction",
  },
  {
    _id: 28,
    first_name: "Dietrich",
    last_name: "Le Sarr",
    email: "dlesarrr@redcross.org",
    gender: "male",
    verified: false,
    created_at: "19/8/2024",
    og: "userAction",
  },
  {
    _id: 29,
    first_name: "Dorry",
    last_name: "Palser",
    email: "dpalsers@ebay.co.uk",
    gender: "female",
    verified: false,
    created_at: "24/2/2024",
    og: "userAction",
  },
  {
    _id: 30,
    first_name: "Perry",
    last_name: "Merigot",
    email: "pmerigott@bbb.org",
    gender: "female",
    verified: false,
    created_at: "10/5/2024",
    og: "userAction",
  },
  {
    _id: 31,
    first_name: "Gussie",
    last_name: "Lummasana",
    email: "glummasanau@arstechnica.com",
    gender: "Non-binary",
    verified: false,
    created_at: "11/9/2023",
    og: "userAction",
  },
  {
    _id: 32,
    first_name: "Jeniffer",
    last_name: "Millichap",
    email: "jmillichapv@github.io",
    gender: "female",
    verified: false,
    created_at: "12/4/2024",
    og: "userAction",
  },
  {
    _id: 33,
    first_name: "Aldous",
    last_name: "Hutcheon",
    email: "ahutcheonw@freewebs.com",
    gender: "male",
    verified: true,
    created_at: "24/11/2023",
    og: "userAction",
  },
  {
    _id: 34,
    first_name: "Kendal",
    last_name: "Scamaden",
    email: "kscamadenx@toplist.cz",
    gender: "male",
    verified: false,
    created_at: "22/4/2024",
    og: "userAction",
  },
  {
    _id: 35,
    first_name: "Donni",
    last_name: "Teaser",
    email: "dteasery@columbia.edu",
    gender: "female",
    verified: true,
    created_at: "25/9/2023",
    og: "userAction",
  },
  {
    _id: 36,
    first_name: "Netti",
    last_name: "Ponting",
    email: "npontingz@taobao.com",
    gender: "female",
    verified: false,
    created_at: "1/2/2024",
    og: "userAction",
  },
  {
    _id: 37,
    first_name: "Udall",
    last_name: "Farman",
    email: "ufarman10@amazon.com",
    gender: "male",
    verified: true,
    created_at: "25/6/2024",
    og: "userAction",
  },
  {
    _id: 38,
    first_name: "Lodovico",
    last_name: "Drabble",
    email: "ldrabble11@phoca.cz",
    gender: "male",
    verified: true,
    created_at: "1/4/2024",
    og: "userAction",
  },
  {
    _id: 39,
    first_name: "Jessey",
    last_name: "Dryden",
    email: "jdryden12@newsvine.com",
    gender: "male",
    verified: true,
    created_at: "3/12/2023",
    og: "userAction",
  },
  {
    _id: 40,
    first_name: "Orion",
    last_name: "Braddock",
    email: "obraddock13@naver.com",
    gender: "male",
    verified: true,
    created_at: "22/6/2024",
    og: "userAction",
  },
  {
    _id: 41,
    first_name: "Analise",
    last_name: "Armytage",
    email: "aarmytage14@gmail.pl",
    gender: "female",
    verified: true,
    created_at: "19/1/2024",
    og: "userAction",
  },
  {
    _id: 42,
    first_name: "Filip",
    last_name: "Hardin",
    email: "fhardin15@yahoo.com.hk",
    gender: "male",
    verified: true,
    created_at: "27/6/2024",
    og: "userAction",
  },
  {
    _id: 43,
    first_name: "Stirling",
    last_name: "Hele",
    email: "shele16@live.org",
    gender: "Genderqueer",
    verified: false,
    created_at: "24/2/2024",
    og: "userAction",
  },
  {
    _id: 44,
    first_name: "Guy",
    last_name: "Feitosa",
    email: "gfeitosa17@clickbank.net",
    gender: "male",
    verified: true,
    created_at: "31/10/2023",
    og: "userAction",
  },
  {
    _id: 45,
    first_name: "Erinn",
    last_name: "Lodwick",
    email: "elodwick18@oakley.com",
    gender: "female",
    verified: false,
    created_at: "15/2/2024",
    og: "userAction",
  },
];

const properties = [
  {
    type: "Residential Land for Sale",
    location: "Iraye, Epe, Lagos",
    image: ASSETS.SAMPLE,
    price: "$24,000",
    size: "1,345 Acres",
    description:
      "3 plots of land Located at mile 2 bus stop opposite century and trindad plaza provides a secluded haven of peace and quiet rugged hill country beauty",
    agentImage: ASSETS.AVATAR,
    agentName: "Ikechukwu Ebube ",
    agentCompany: "Associate/Company name ",
  },
  {
    type: "Residential Land for Sale",
    location: "Iraye, Epe, Lagos",
    image: ASSETS.SAMPLE,
    price: "$24,000",
    size: "1,345 Acres",
    description:
      "3 plots of land Located at mile 2 bus stop opposite century and trindad plaza provides a secluded haven of peace and quiet rugged hill country beauty",
    agentImage: ASSETS.AVATAR,
    agentName: "Ikechukwu Ebube ",
    agentCompany: "Associate/Company name ",
  },
  {
    type: "Residential Land for Sale",
    location: "Iraye, Epe, Lagos",
    image: ASSETS.SAMPLE,
    price: "$24,000",
    size: "1,345 Acres",
    description:
      "3 plots of land Located at mile 2 bus stop opposite century and trindad plaza provides a secluded haven of peace and quiet rugged hill country beauty",
    agentImage: ASSETS.AVATAR,
    agentName: "Ikechukwu Ebube ",
    agentCompany: "Associate/Company name ",
  },
  {
    type: "Residential Land for Sale",
    location: "Iraye, Epe, Lagos",
    image: ASSETS.SAMPLE,
    price: "$24,000",
    size: "1,345 Acres",
    description:
      "3 plots of land Located at mile 2 bus stop opposite century and trindad plaza provides a secluded haven of peace and quiet rugged hill country beauty",
    agentImage: ASSETS.AVATAR,
    agentName: "Ikechukwu Ebube ",
    agentCompany: "Associate/Company name ",
  },
  {
    type: "Residential Land for Sale",
    location: "Iraye, Epe, Lagos",
    image: ASSETS.SAMPLE,
    price: "$24,000",
    size: "1,345 Acres",
    description:
      "3 plots of land Located at mile 2 bus stop opposite century and trindad plaza provides a secluded haven of peace and quiet rugged hill country beauty",
    agentImage: ASSETS.AVATAR,
    agentName: "Ikechukwu Ebube ",
    agentCompany: "Associate/Company name ",
  },
  {
    type: "Residential Land for Sale",
    location: "Iraye, Epe, Lagos",
    image: ASSETS.SAMPLE,
    price: "$24,000",
    size: "1,345 Acres",
    description:
      "3 plots of land Located at mile 2 bus stop opposite century and trindad plaza provides a secluded haven of peace and quiet rugged hill country beauty",
    agentImage: ASSETS.AVATAR,
    agentName: "Ikechukwu Ebube ",
    agentCompany: "Associate/Company name ",
  },
];

const totalData = [
  {
    no: 48,
    item: "Total Properties",
    description: "Land and Building structures inclusive",
  },
  {
    no: 67,
    item: "Total Agents",
    description: "Verified and Unverified Agents",
  },
  {
    no: 250,
    item: "Total Clients",
    description: "Active and Unactive Registered Client",
  },
  {
    no: "$24,000",
    item: "Total Revenue",
    description: "From all Verified Properties",
  },
];

const agentData = [
  {
    id: 1,
    name: "Glenna",
    email: "Collick",
    gender: "gcollicka@twitter.com",
    location: "female",
  },
  {
    id: 2,
    name: "Kin",
    email: "Pietranek",
    gender: "kpietranekb@hp.com",
    location: "male",
  },
  {
    id: 3,
    name: "Lexy",
    email: "Lavallin",
    gender: "llavallinc@ucla.edu",
    location: "female",
  },
  {
    id: 4,
    name: "Colin",
    email: "Zelland",
    gender: "czellandd@scientificamerican.com",
    location: "male",
  },
  {
    id: 5,
    name: "Deborah",
    email: "Whanstall",
    gender: "dwhanstalle@senate.gov",
    location: "female",
  },
  {
    id: 6,
    name: "Rosaleen",
    email: "Andrivel",
    gender: "randrivelf@timesonline.co.uk",
    location: "Polygender",
  },
  {
    id: 7,
    name: "Brit",
    email: "Bedham",
    gender: "bbedhamg@gmail.com",
    location: "male",
  },
];
const clientData = [
  {
    id: 1,
    name: "Rosalia",
    email: "Ashingden",
    gender: "rashingden0@icq.com",
    location: "female",
  },
  {
    id: 2,
    name: "Adolphus",
    email: "Rutt",
    gender: "arutt1@macromedia.com",
    location: "Agender",
  },
  {
    id: 3,
    name: "Kelli",
    email: "Ornils",
    gender: "kornils2@hao123.com",
    location: "female",
  },
  {
    id: 4,
    name: "Liva",
    email: "Laux",
    gender: "llaux3@upenn.edu",
    location: "female",
  },
  {
    id: 5,
    name: "Jan",
    email: "Selvester",
    gender: "jselvester4@cam.ac.uk",
    location: "male",
  },
  {
    id: 6,
    name: "Albertine",
    email: "Mudle",
    gender: "amudle5@unesco.org",
    location: "female",
  },
  {
    id: 7,
    name: "Christin",
    email: "Niset",
    gender: "cniset6@lycos.com",
    location: "Genderfluid",
  },
];

module.exports = {
  users,
  properties,
  tickets,
  totalData,
  clientData,
  agentData,
};
